### ISSUE TITLE
Problem beim Installieren

### ISSUE THREAD

**Issue by nickbe** [liob/OXadminGUI#2]
Hi Peter,

wir sind gerade über dein Admin-GUI gestolpert.
Zuerst mal, wir finden dass gehört unbedingt weiter am leben erhalten :)

Zum anderen könnten wir Deine Hilfe gebrauchen (wenn Du denn Zeit findest) da wir nicht in der Lage waren das Ding zu installieren.

Wenn wir die fertige .jar version downloaden, diese dann in das Verz. 'bundles' kopieren und dann den Server neu starten schlägt der Aufruf 'xxx.unseredomain.de/servlet/webserver/index.html' mit dem Fehler 'Resource identified by path '/servlet/webserver/index.html', does not exist.' fehl.

Ich vermute mal wir machen hier was grundsätzliches falsch.
Cheers
Nick

**Comment by liob** [comment]
Ich bin nicht Peter. Verwenden Sie Grizzly?

**Comment by nickbe** [comment]
Nicht das ich wüsste

**Comment by liob** [comment]
Wenn Sie kein Grizzly verwenden, wird dieser Fork wahrscheinlich nicht funktionieren. Ich würde Ihnen empfehlen die ursprüngliche Version zu testen.

This is a fork of [Peter’s OX Server Admin GUI](OXadminGUI) version [0.1.17] to fix an issue when utilized with grizzly [1](https://forum.open-xchange.com/showthread.php?3750-Peter-s-Open-Xchange-Server-Admin-GUI&p=27021#post27021).
